-- EduFlow: importação de aulas do Google Drive
-- Cole no SQL Editor do Supabase e clique em Run

DO $$
DECLARE
  sid integer;
BEGIN

  -- História do Brasil
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('História do Brasil')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Panorama geral periodo colonial', 'https://drive.google.com/file/d/1J3sCdTEjiX_fuHtxyV04vdGBswbrGZXn/view', 'https://drive.google.com/file/d/1J3sCdTEjiX_fuHtxyV04vdGBswbrGZXn/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'O Bandeirantismo', 'https://drive.google.com/file/d/18QiCcG3WTXXzi3ZqVXSDIbYdzlgH75Fx/view', 'https://drive.google.com/file/d/18QiCcG3WTXXzi3ZqVXSDIbYdzlgH75Fx/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/1A60CxbTI1FS1Ey5PHlR0yWGtpHUmuHf8/view', 'https://drive.google.com/file/d/1A60CxbTI1FS1Ey5PHlR0yWGtpHUmuHf8/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'O Seculo do Ouro', 'https://drive.google.com/file/d/1LxqY8HXtiAQTz-NXN21vq06PNGh95QLA/view', 'https://drive.google.com/file/d/1LxqY8HXtiAQTz-NXN21vq06PNGh95QLA/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Alexandre de Gusmao Tratado de Madri', 'https://drive.google.com/file/d/1yL--3GCWU6_4gVwLDnLz9VlrDdYcVGKD/view', 'https://drive.google.com/file/d/1yL--3GCWU6_4gVwLDnLz9VlrDdYcVGKD/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/1aSzCmRt5bRJrGza7JINuiQyPyD4puZE2/view', 'https://drive.google.com/file/d/1aSzCmRt5bRJrGza7JINuiQyPyD4puZE2/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Periodo Pombalino e Gov Dona Maria', 'https://drive.google.com/file/d/1h0J8AuIo3FhaQzXf1CrqqyynxQ-hLxlT/view', 'https://drive.google.com/file/d/1h0J8AuIo3FhaQzXf1CrqqyynxQ-hLxlT/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Periodo joanino', 'https://drive.google.com/file/d/1NpOImCdDTjHe6-KRh8fY6Jj-_Ldn9reM/view', 'https://drive.google.com/file/d/1NpOImCdDTjHe6-KRh8fY6Jj-_Ldn9reM/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/19LSff5lul4Vnzg-49YY4BZXbXc0NOrmP/view', 'https://drive.google.com/file/d/19LSff5lul4Vnzg-49YY4BZXbXc0NOrmP/preview', 9);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Processo de Independencia', 'https://drive.google.com/file/d/1cgaG8Tyemc1itNv-GIWdgkUk14mxQAnY/view', 'https://drive.google.com/file/d/1cgaG8Tyemc1itNv-GIWdgkUk14mxQAnY/preview', 10);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Historiografia Processo Independencia', 'https://drive.google.com/file/d/1GACNgfZaJleT9HoFIL6i5cU5a4I4Eu1u/view', 'https://drive.google.com/file/d/1GACNgfZaJleT9HoFIL6i5cU5a4I4Eu1u/preview', 11);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/1f689Ik4b3q_TkLyhNQmSE599JhQRmg1F/view', 'https://drive.google.com/file/d/1f689Ik4b3q_TkLyhNQmSE599JhQRmg1F/preview', 12);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Primeiro Reinado 1822 1831', 'https://drive.google.com/file/d/1Oh7u4HdxZKqOh7sIyQAH56LpfluEalmJ/view', 'https://drive.google.com/file/d/1Oh7u4HdxZKqOh7sIyQAH56LpfluEalmJ/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Regencia 1831-1840', 'https://drive.google.com/file/d/10ySdwFpXvAT5t3O7CvrQqDpVaSQxVYYj/view', 'https://drive.google.com/file/d/10ySdwFpXvAT5t3O7CvrQqDpVaSQxVYYj/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/1ln8xLWMC3LcA0zIwh3boeBh7dB7CiKpH/view', 'https://drive.google.com/file/d/1ln8xLWMC3LcA0zIwh3boeBh7dB7CiKpH/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Consolidacao do Imperio 1840-1853', 'https://drive.google.com/file/d/14Ut5whw4Skl7CjF6fSDwsXIX3Q0omp8-/view', 'https://drive.google.com/file/d/14Ut5whw4Skl7CjF6fSDwsXIX3Q0omp8-/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica Externa Brasileira 1822-1852', 'https://drive.google.com/file/d/1XLl9dc6xPRvRbwedPYSS87qxcSnaaIVV/view', 'https://drive.google.com/file/d/1XLl9dc6xPRvRbwedPYSS87qxcSnaaIVV/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/1jgN9K5VyHcj5Pes6yGXSOtO2E1yEoLFG/view', 'https://drive.google.com/file/d/1jgN9K5VyHcj5Pes6yGXSOtO2E1yEoLFG/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'GSintese Gabinetes do Imperio', 'https://drive.google.com/file/d/1_0KAqW5lbavjjd0i-B-2b_oioVt1Do6Q/view', 'https://drive.google.com/file/d/1_0KAqW5lbavjjd0i-B-2b_oioVt1Do6Q/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Economia do Imperio', 'https://drive.google.com/file/d/1PSXFiqa4sIjHb-suRXMfc4MyUtTQZI5g/view', 'https://drive.google.com/file/d/1PSXFiqa4sIjHb-suRXMfc4MyUtTQZI5g/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1IDwiKvLK6W4pDmz-wfs5A6FPEHOxwORd/view', 'https://drive.google.com/file/d/1IDwiKvLK6W4pDmz-wfs5A6FPEHOxwORd/preview', 109);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Cultura no Imperio', 'https://drive.google.com/file/d/1ig8TsxVqMlRAp04oQgeBpk-Rsde8FuEg/view', 'https://drive.google.com/file/d/1ig8TsxVqMlRAp04oQgeBpk-Rsde8FuEg/preview', 110);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Guerra do Paraguai', 'https://drive.google.com/file/d/1l_qww45NC-7yPAlfTs2Ykvs-d_gAl7t0/view', 'https://drive.google.com/file/d/1l_qww45NC-7yPAlfTs2Ykvs-d_gAl7t0/preview', 111);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/10aKgKVTwwIB7fZNG0iA3cQ2nnddF10bx/view', 'https://drive.google.com/file/d/10aKgKVTwwIB7fZNG0iA3cQ2nnddF10bx/preview', 112);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Geracao de 1870 Crise do Imperio', 'https://drive.google.com/file/d/18ceb_4Ed9wNgsXuPEHWlUe-ZdEVub_bT/view', 'https://drive.google.com/file/d/18ceb_4Ed9wNgsXuPEHWlUe-ZdEVub_bT/preview', 113);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Abolicionismo Republicanismo', 'https://drive.google.com/file/d/1MnvjM_x7Jbrc2Ro0WKH5m4TSac-UBMhe/view', 'https://drive.google.com/file/d/1MnvjM_x7Jbrc2Ro0WKH5m4TSac-UBMhe/preview', 114);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria5', 'https://drive.google.com/file/d/1YeykSQcnSQFacN842f6sLRkxNZ2ptzED/view', 'https://drive.google.com/file/d/1YeykSQcnSQFacN842f6sLRkxNZ2ptzED/preview', 115);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica Externa 2o Reinado', 'https://drive.google.com/file/d/1vcTzvJ4gr4jwa23zZvvNGU6zcAaY2Gx-/view', 'https://drive.google.com/file/d/1vcTzvJ4gr4jwa23zZvvNGU6zcAaY2Gx-/preview', 116);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Proclamacao da Republica', 'https://drive.google.com/file/d/1nqYoexSbJYxbLg7iKiSoMxQkBimOBRAU/view', 'https://drive.google.com/file/d/1nqYoexSbJYxbLg7iKiSoMxQkBimOBRAU/preview', 117);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria6', 'https://drive.google.com/file/d/10IwSWntcdPVFjLQD_q0zkpep7X-O6zW5/view', 'https://drive.google.com/file/d/10IwSWntcdPVFjLQD_q0zkpep7X-O6zW5/preview', 118);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Anos entropicos', 'https://drive.google.com/file/d/14ripVFheyiJNI1Hx9Q0APzh-n5pOWasc/view', 'https://drive.google.com/file/d/14ripVFheyiJNI1Hx9Q0APzh-n5pOWasc/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Campos salles colmeia oligarquica', 'https://drive.google.com/file/d/123pqNf0F9gnU1ar2oIRzKDmI7bLu4RgF/view', 'https://drive.google.com/file/d/123pqNf0F9gnU1ar2oIRzKDmI7bLu4RgF/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/15LKgFDmbZK2g1yGDQf8IA0KyL2-NVimO/view', 'https://drive.google.com/file/d/15LKgFDmbZK2g1yGDQf8IA0KyL2-NVimO/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica externa rio branco', 'https://drive.google.com/file/d/1RX75UBtq53yeT8RUOg-WR_r8XuKl-ve1/view', 'https://drive.google.com/file/d/1RX75UBtq53yeT8RUOg-WR_r8XuKl-ve1/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Movimentos sociais primeira republica', 'https://drive.google.com/file/d/1WNEqJK-p1XdQJDluwoJw8kGW5CMfVdZX/view', 'https://drive.google.com/file/d/1WNEqJK-p1XdQJDluwoJw8kGW5CMfVdZX/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/1LpKH3sikSaHtwKrn_2ctUHLps-zc8j1B/view', 'https://drive.google.com/file/d/1LpKH3sikSaHtwKrn_2ctUHLps-zc8j1B/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Militares poder desestabilizador', 'https://drive.google.com/file/d/1zvYJQNFt3mhhmhrV7vrfLIJkudsxMo4T/view', 'https://drive.google.com/file/d/1zvYJQNFt3mhhmhrV7vrfLIJkudsxMo4T/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica externa anos 1920', 'https://drive.google.com/file/d/1nU6U_QryLuS9QwjiuSGo3B4Sevrlb1Hu/view', 'https://drive.google.com/file/d/1nU6U_QryLuS9QwjiuSGo3B4Sevrlb1Hu/preview', 208);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1DKcwE8VjXUIznyUaEqlAI_pEcTZSLLYS/view', 'https://drive.google.com/file/d/1DKcwE8VjXUIznyUaEqlAI_pEcTZSLLYS/preview', 209);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Crises 1a republica revolucao 1930', 'https://drive.google.com/file/d/1GZl-krGEOkW5FV97KRt4rNcEc767alHK/view', 'https://drive.google.com/file/d/1GZl-krGEOkW5FV97KRt4rNcEc767alHK/preview', 210);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Era  vargas', 'https://drive.google.com/file/d/1ViLhtFFIuagNs6n5gqW4XlNg1LUyJy-4/view', 'https://drive.google.com/file/d/1ViLhtFFIuagNs6n5gqW4XlNg1LUyJy-4/preview', 211);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/1eXPsmLVjDlh-sbBZOpCaPG4vwzThIevo/view', 'https://drive.google.com/file/d/1eXPsmLVjDlh-sbBZOpCaPG4vwzThIevo/preview', 212);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Era vargas estado novo', 'https://drive.google.com/file/d/1XUZVQ6FCMCD_ZODbnycunWBcP1HgN1lx/view', 'https://drive.google.com/file/d/1XUZVQ6FCMCD_ZODbnycunWBcP1HgN1lx/preview', 213);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Era vargas politica externa', 'https://drive.google.com/file/d/1Y3Nph6J5550WtdoKGFLOGFZ2YNM53Am3/view', 'https://drive.google.com/file/d/1Y3Nph6J5550WtdoKGFLOGFZ2YNM53Am3/preview', 214);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria5', 'https://drive.google.com/file/d/1IyWzb_76kFg5g9XCFWrGjawto4WtFTye/view', 'https://drive.google.com/file/d/1IyWzb_76kFg5g9XCFWrGjawto4WtFTye/preview', 215);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria6', 'https://drive.google.com/file/d/1MVZ-K6OsmFHJ7ctOz_xjMrXXj1LjfQFA/view', 'https://drive.google.com/file/d/1MVZ-K6OsmFHJ7ctOz_xjMrXXj1LjfQFA/preview', 216);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Era vargas-industrializacao crise estado novo', 'https://drive.google.com/file/d/1qEpI8kdQOHdO-2u7eQTZxZIsqywA0SkH/view', 'https://drive.google.com/file/d/1qEpI8kdQOHdO-2u7eQTZxZIsqywA0SkH/preview', 301);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Redemocratizaca gov dutra', 'https://drive.google.com/file/d/1W93Qxp-IWABa65fnLK7lf_DRMnxK360m/view', 'https://drive.google.com/file/d/1W93Qxp-IWABa65fnLK7lf_DRMnxK360m/preview', 302);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/1slV0gpFw3OOUlRrxop3XbDFKqLvHBseY/view', 'https://drive.google.com/file/d/1slV0gpFw3OOUlRrxop3XbDFKqLvHBseY/preview', 303);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Transicao segundo vargas e jk', 'https://drive.google.com/file/d/1pOwgcF-fJh592q_b4a8k5xR-78H_elCh/view', 'https://drive.google.com/file/d/1pOwgcF-fJh592q_b4a8k5xR-78H_elCh/preview', 304);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Janio jango', 'https://drive.google.com/file/d/1f5wMdzG2zI7nVlYeRIbk6wQblWfWfETB/view', 'https://drive.google.com/file/d/1f5wMdzG2zI7nVlYeRIbk6wQblWfWfETB/preview', 305);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/1QkBvl7HTqzMyLMtj3rvGRnGbpoFTyuX1/view', 'https://drive.google.com/file/d/1QkBvl7HTqzMyLMtj3rvGRnGbpoFTyuX1/preview', 306);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Castelo branco costa e silva', 'https://drive.google.com/file/d/1YjRz_y0zhgXr1oUM4llQKMqfU2VrPtmw/view', 'https://drive.google.com/file/d/1YjRz_y0zhgXr1oUM4llQKMqfU2VrPtmw/preview', 307);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Const 1967 medici', 'https://drive.google.com/file/d/1WVwHkqorCqeDyiw8auI3tRvA-JStwnS3/view', 'https://drive.google.com/file/d/1WVwHkqorCqeDyiw8auI3tRvA-JStwnS3/preview', 308);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1_MaYYjBI0k88zYtjnAS5KELwYoaGMhXs/view', 'https://drive.google.com/file/d/1_MaYYjBI0k88zYtjnAS5KELwYoaGMhXs/preview', 309);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Geisel', 'https://drive.google.com/file/d/1Y3TNRsqRiHasyCytclLlFp9sdRR2XcC_/view', 'https://drive.google.com/file/d/1Y3TNRsqRiHasyCytclLlFp9sdRR2XcC_/preview', 310);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Figueiredo', 'https://drive.google.com/file/d/1OHiXhLr8taQiklGfkvMZb4n-tCm_EwlZ/view', 'https://drive.google.com/file/d/1OHiXhLr8taQiklGfkvMZb4n-tCm_EwlZ/preview', 311);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica externa regime militar', 'https://drive.google.com/file/d/1pmsIiEsLAhqhB1KAkc8mhZOJuchBrIvj/view', 'https://drive.google.com/file/d/1pmsIiEsLAhqhB1KAkc8mhZOJuchBrIvj/preview', 312);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Diplomacia cultural regime militar', 'https://drive.google.com/file/d/1RxZ1DQjQjjEAF3oMvKnnsDM5NxFjg2-h/view', 'https://drive.google.com/file/d/1RxZ1DQjQjjEAF3oMvKnnsDM5NxFjg2-h/preview', 313);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes bilaterais brasil argentina', 'https://drive.google.com/file/d/1c2rrWP6L92na5dtgzI1gqKpSJo7lzpRi/view', 'https://drive.google.com/file/d/1c2rrWP6L92na5dtgzI1gqKpSJo7lzpRi/preview', 314);
  END IF;

  -- História Mundial
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('História Mundial')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Absolutismo mercantilismo rev inglesas', 'https://drive.google.com/file/d/1v19AD1gEjXeZKWqk_40XbXVhsojxU_sQ/view', 'https://drive.google.com/file/d/1v19AD1gEjXeZKWqk_40XbXVhsojxU_sQ/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Iluminismo rev francesa', 'https://drive.google.com/file/d/1BO6jRVkI9i1V7Q2mve0csGRKHm2XIzkO/view', 'https://drive.google.com/file/d/1BO6jRVkI9i1V7Q2mve0csGRKHm2XIzkO/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/19aT8IvjRAu6PhN0RAVgTvfTv8TiLsKkk/view', 'https://drive.google.com/file/d/19aT8IvjRAu6PhN0RAVgTvfTv8TiLsKkk/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Periodo napoleonico congresso de viena p1', 'https://drive.google.com/file/d/1765PiDkXvCJp1RWqGoHKZtVAbNChJHRf/view', 'https://drive.google.com/file/d/1765PiDkXvCJp1RWqGoHKZtVAbNChJHRf/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Periodo napoleonico congresso de viena p2', 'https://drive.google.com/file/d/19svKbKNGifTV3AUHfby3tatYNU23gtsZ/view', 'https://drive.google.com/file/d/19svKbKNGifTV3AUHfby3tatYNU23gtsZ/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/13n4UBo0SL_yVV62EifyTKpyRIx6anrzm/view', 'https://drive.google.com/file/d/13n4UBo0SL_yVV62EifyTKpyRIx6anrzm/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Liberalismo unificacoes 1820 1890 p1', 'https://drive.google.com/file/d/1TKzX1qZyN_MBPcIDUre6LNyc1tsITEV3/view', 'https://drive.google.com/file/d/1TKzX1qZyN_MBPcIDUre6LNyc1tsITEV3/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Liberalismo unificacoes 1820 1890 p2', 'https://drive.google.com/file/d/1YgEAbWF7ScdLsmYs11rN4zf6fP1egM54/view', 'https://drive.google.com/file/d/1YgEAbWF7ScdLsmYs11rN4zf6fP1egM54/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1cltbZlFyW27U38QYudZl7qm_zYZ9o4KQ/view', 'https://drive.google.com/file/d/1cltbZlFyW27U38QYudZl7qm_zYZ9o4KQ/preview', 9);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Imperialismo teoria estudos de casos', 'https://drive.google.com/file/d/1XEpm8btXtGOXMcv3u8SxWOr8AZjJh2Ji/view', 'https://drive.google.com/file/d/1XEpm8btXtGOXMcv3u8SxWOr8AZjJh2Ji/preview', 10);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'EUA da Independencia a marcha para oeste', 'https://drive.google.com/file/d/11ty4EWzxKz91dGkZRBZ3Ezs9NXr0lyM6/view', 'https://drive.google.com/file/d/11ty4EWzxKz91dGkZRBZ3Ezs9NXr0lyM6/preview', 11);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/1faOTqsgQ0TpX7kDUAhJJDvEWCxGaENR5/view', 'https://drive.google.com/file/d/1faOTqsgQ0TpX7kDUAhJJDvEWCxGaENR5/preview', 12);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'EUA Guerra Civil ao Big Stick', 'https://drive.google.com/file/d/1ub4Ps6hX3Dp7ZfM7PLPxondz1auvLRFu/view', 'https://drive.google.com/file/d/1ub4Ps6hX3Dp7ZfM7PLPxondz1auvLRFu/preview', 13);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'America latina sec XIX', 'https://drive.google.com/file/d/1hiZfPmX3zBWLxi8gYk-VpjfTZEwvWMPK/view', 'https://drive.google.com/file/d/1hiZfPmX3zBWLxi8gYk-VpjfTZEwvWMPK/preview', 14);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria5', 'https://drive.google.com/file/d/1S6a5VROJKK_eBynT1P3Umk7kgyrtpyLd/view', 'https://drive.google.com/file/d/1S6a5VROJKK_eBynT1P3Umk7kgyrtpyLd/preview', 15);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'O mundo entre 1890 1914', 'https://drive.google.com/file/d/1AO7UZCE6vq9h3RZXTCaMN47qw-nC7TOW/view', 'https://drive.google.com/file/d/1AO7UZCE6vq9h3RZXTCaMN47qw-nC7TOW/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Primeira guerra mundial', 'https://drive.google.com/file/d/1ZVo6B94_GPKSPkHlNoZfvamcFW0eCw5X/view', 'https://drive.google.com/file/d/1ZVo6B94_GPKSPkHlNoZfvamcFW0eCw5X/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/1bCIzRev17Kzd_ZTwWtjcEcerJ7kBT04M/view', 'https://drive.google.com/file/d/1bCIzRev17Kzd_ZTwWtjcEcerJ7kBT04M/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Entre guerras ascencao fascimo', 'https://drive.google.com/file/d/1W3vjb6kiX-q7GoxDjII-peyEXwy5tsFw/view', 'https://drive.google.com/file/d/1W3vjb6kiX-q7GoxDjII-peyEXwy5tsFw/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Segunda guerra mundial', 'https://drive.google.com/file/d/15HFmqXLKdAkfstlObLxWA2r7uugM6Puh/view', 'https://drive.google.com/file/d/15HFmqXLKdAkfstlObLxWA2r7uugM6Puh/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/1qm7OErhLOS3iBKCiND7SV6lmPT7Ieka2/view', 'https://drive.google.com/file/d/1qm7OErhLOS3iBKCiND7SV6lmPT7Ieka2/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Segunda guerra mundial p2', 'https://drive.google.com/file/d/1o_SO-bhQ5jzxXiH8COLJhrpxdb1osRX2/view', 'https://drive.google.com/file/d/1o_SO-bhQ5jzxXiH8COLJhrpxdb1osRX2/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Guerra fria montagem do sistema', 'https://drive.google.com/file/d/1l1HGobQMORzj_hheHqz-YrIkxgcm42mQ/view', 'https://drive.google.com/file/d/1l1HGobQMORzj_hheHqz-YrIkxgcm42mQ/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1v0QwTjVVH2011Bc4bzvtgCKItCk4kpt4/view', 'https://drive.google.com/file/d/1v0QwTjVVH2011Bc4bzvtgCKItCk4kpt4/preview', 109);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Guerra fria apogeu detente', 'https://drive.google.com/file/d/1SYB0jjUySj8NmsiuAoo5pjZycoYq14nl/view', 'https://drive.google.com/file/d/1SYB0jjUySj8NmsiuAoo5pjZycoYq14nl/preview', 110);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Lutas libertacao colonial', 'https://drive.google.com/file/d/1KB_sFp72fPNYGrvhZH-FqdJPaT6jelLq/view', 'https://drive.google.com/file/d/1KB_sFp72fPNYGrvhZH-FqdJPaT6jelLq/preview', 111);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/18-1dyOrWqYjlBdf3SLFmWUCs9Dbfqu74/view', 'https://drive.google.com/file/d/18-1dyOrWqYjlBdf3SLFmWUCs9Dbfqu74/preview', 112);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Mundo socialista colapso urss', 'https://drive.google.com/file/d/1eIy3P0L-Nvo2hfWLJ4X86yCDIVCzKyCp/view', 'https://drive.google.com/file/d/1eIy3P0L-Nvo2hfWLJ4X86yCDIVCzKyCp/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Sistemas internacionais metternich bismarch pax britanica bipolaridade', 'https://drive.google.com/file/d/1DCQ_wzgxsYrfKtL18_z1cmHz7ZYBiM3N/view', 'https://drive.google.com/file/d/1DCQ_wzgxsYrfKtL18_z1cmHz7ZYBiM3N/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria1', 'https://drive.google.com/file/d/10UbjjC420JndnH6zzIIDe5Y3iK0wlDr-/view', 'https://drive.google.com/file/d/10UbjjC420JndnH6zzIIDe5Y3iK0wlDr-/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'America latina sec xx', 'https://drive.google.com/file/d/1gU2yCSfxGgWR1cBkyAekjNpAgNIJpvCb/view', 'https://drive.google.com/file/d/1gU2yCSfxGgWR1cBkyAekjNpAgNIJpvCb/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'America latina sec xx p2', 'https://drive.google.com/file/d/1MuA9oWw_MGX92LTOhV5sFpZ9Vq1MwizK/view', 'https://drive.google.com/file/d/1MuA9oWw_MGX92LTOhV5sFpZ9Vq1MwizK/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria2', 'https://drive.google.com/file/d/1j_NDcNiukjv8rs0aEBpxjYUiGfXL6Hcf/view', 'https://drive.google.com/file/d/1j_NDcNiukjv8rs0aEBpxjYUiGfXL6Hcf/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Panorama cultural europeu sec xix', 'https://drive.google.com/file/d/1KVVzaLDxLQm-tiYw7Xrw1d1mJO5vyKCr/view', 'https://drive.google.com/file/d/1KVVzaLDxLQm-tiYw7Xrw1d1mJO5vyKCr/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Panorama cultural europeu 1a metade sec xx', 'https://drive.google.com/file/d/1FPMIaS1MZxYgvSHQcDdwN3F4oHfdIbP-/view', 'https://drive.google.com/file/d/1FPMIaS1MZxYgvSHQcDdwN3F4oHfdIbP-/preview', 208);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria3', 'https://drive.google.com/file/d/1WOaC8xQY7YB25zfj30CBxh2P2DU-2I8m/view', 'https://drive.google.com/file/d/1WOaC8xQY7YB25zfj30CBxh2P2DU-2I8m/preview', 209);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Panorama cultural eua america latina sec xx', 'https://drive.google.com/file/d/1NhSZniDETVI01EuASEQYVWNftAtAfR9l/view', 'https://drive.google.com/file/d/1NhSZniDETVI01EuASEQYVWNftAtAfR9l/preview', 210);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/16sKCJLGO3drVhA3HtVuiBUVnOpC14sJm/view', 'https://drive.google.com/file/d/16sKCJLGO3drVhA3HtVuiBUVnOpC14sJm/preview', 211);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Africanismo pensamento africanista sec xx', 'https://drive.google.com/file/d/1CjTVNzX_h1DBkzTOL36MnDJ9eRyNQYYt/view', 'https://drive.google.com/file/d/1CjTVNzX_h1DBkzTOL36MnDJ9eRyNQYYt/preview', 212);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monitoria4', 'https://drive.google.com/file/d/1h1evrJY_mQTKouch3Ctu3L9MKGcasTW_/view', 'https://drive.google.com/file/d/1h1evrJY_mQTKouch3Ctu3L9MKGcasTW_/preview', 213);
  END IF;

  -- Português
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Português')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula1', 'https://drive.google.com/file/d/1euER-KBrusAlmQfe57YbvQwttzjwUKur/view', 'https://drive.google.com/file/d/1euER-KBrusAlmQfe57YbvQwttzjwUKur/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula2', 'https://drive.google.com/file/d/1pZabhjmE245HQGbem10P7KQhp27ENWrd/view', 'https://drive.google.com/file/d/1pZabhjmE245HQGbem10P7KQhp27ENWrd/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula3', 'https://drive.google.com/file/d/1UsdPsCb4qUL2Qy2567W75WjEJUf19JZp/view', 'https://drive.google.com/file/d/1UsdPsCb4qUL2Qy2567W75WjEJUf19JZp/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula4', 'https://drive.google.com/file/d/1p6-7uw17eQ00a4myC2p5lRcXfY7_aADy/view', 'https://drive.google.com/file/d/1p6-7uw17eQ00a4myC2p5lRcXfY7_aADy/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula5', 'https://drive.google.com/file/d/1K1DUZ8bZej_WakokLose41YZuHCCpAFV/view', 'https://drive.google.com/file/d/1K1DUZ8bZej_WakokLose41YZuHCCpAFV/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula6', 'https://drive.google.com/file/d/10Sqnxu4-Ea1eKFEy78yQU_lppEQwd4BP/view', 'https://drive.google.com/file/d/10Sqnxu4-Ea1eKFEy78yQU_lppEQwd4BP/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula7', 'https://drive.google.com/file/d/1d5yd2O5yCe5QdBsF1glxnNXV0yyPBTZn/view', 'https://drive.google.com/file/d/1d5yd2O5yCe5QdBsF1glxnNXV0yyPBTZn/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula8', 'https://drive.google.com/file/d/1IdXlRk2d5jJflM8qUfhHv9s-IUadM1HZ/view', 'https://drive.google.com/file/d/1IdXlRk2d5jJflM8qUfhHv9s-IUadM1HZ/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula1', 'https://drive.google.com/file/d/18qneZ-vbFxjOqFVN1L7V0Qdb1UPg22R1/view', 'https://drive.google.com/file/d/18qneZ-vbFxjOqFVN1L7V0Qdb1UPg22R1/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula2', 'https://drive.google.com/file/d/1Tt00seirx_TKTO8Wf9d_kqIEyMYYM32l/view', 'https://drive.google.com/file/d/1Tt00seirx_TKTO8Wf9d_kqIEyMYYM32l/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula3', 'https://drive.google.com/file/d/1HtdgdUUz-TmnDM7RrnGbrp0nPFwbetES/view', 'https://drive.google.com/file/d/1HtdgdUUz-TmnDM7RrnGbrp0nPFwbetES/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula4', 'https://drive.google.com/file/d/19kqrTSdY3GCMJIrEXjzlJk0jsU4tgOks/view', 'https://drive.google.com/file/d/19kqrTSdY3GCMJIrEXjzlJk0jsU4tgOks/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula5', 'https://drive.google.com/file/d/1KUivEtgIr5Atzmrsv6jeEfcddIbFVP9l/view', 'https://drive.google.com/file/d/1KUivEtgIr5Atzmrsv6jeEfcddIbFVP9l/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula6', 'https://drive.google.com/file/d/1ITJOBFUj24CVXpQ6Cl2i5KVQvfTP1JiF/view', 'https://drive.google.com/file/d/1ITJOBFUj24CVXpQ6Cl2i5KVQvfTP1JiF/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula7', 'https://drive.google.com/file/d/1ANFoxzgKdhMg1eofIHkyZ6CfwHryS-t8/view', 'https://drive.google.com/file/d/1ANFoxzgKdhMg1eofIHkyZ6CfwHryS-t8/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'aula8', 'https://drive.google.com/file/d/1yAHdVIASlh66TDJGn-RILLpsjUNMZgOW/view', 'https://drive.google.com/file/d/1yAHdVIASlh66TDJGn-RILLpsjUNMZgOW/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Colocacao pronominal', 'https://drive.google.com/file/d/1kJm9AWDXkce0n7-DwAFnRLAXCxf2ikJG/view', 'https://drive.google.com/file/d/1kJm9AWDXkce0n7-DwAFnRLAXCxf2ikJG/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Concordancia nominal', 'https://drive.google.com/file/d/1n_d4Dc4tqHN339IsJM7GWdmdKI8GLI0T/view', 'https://drive.google.com/file/d/1n_d4Dc4tqHN339IsJM7GWdmdKI8GLI0T/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Concordancia verbal', 'https://drive.google.com/file/d/138yv3qmaS1YSTKoyfmyphi9FGD7gb36s/view', 'https://drive.google.com/file/d/138yv3qmaS1YSTKoyfmyphi9FGD7gb36s/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pontuacao', 'https://drive.google.com/file/d/12YkCyJvEgcLX5PiCkWgC4s3Dagr6mgPH/view', 'https://drive.google.com/file/d/12YkCyJvEgcLX5PiCkWgC4s3Dagr6mgPH/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Figuras linguagem', 'https://drive.google.com/file/d/13o7gRnRBsaHqaqmYB3FWIdEm-UG8i69l/view', 'https://drive.google.com/file/d/13o7gRnRBsaHqaqmYB3FWIdEm-UG8i69l/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estilistica poetica', 'https://drive.google.com/file/d/1xEIORUs0GKB7RK_9UutdHtobBR-54Vd-/view', 'https://drive.google.com/file/d/1xEIORUs0GKB7RK_9UutdHtobBR-54Vd-/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Literatura brasil1', 'https://drive.google.com/file/d/1rxcwGGpGvUsBxrl8lGQeNQw9VMaSfQK1/view', 'https://drive.google.com/file/d/1rxcwGGpGvUsBxrl8lGQeNQw9VMaSfQK1/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Literatura brasil2', 'https://drive.google.com/file/d/151owUp8XTh1-jynYa_EbB0vQaaGbubsy/view', 'https://drive.google.com/file/d/151owUp8XTh1-jynYa_EbB0vQaaGbubsy/preview', 208);
  END IF;

  -- Inglês
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Inglês')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'The start', 'https://drive.google.com/file/d/1k9ZCQiQiIMwaWZT5m7YxIbg0uRuYWE02/view', 'https://drive.google.com/file/d/1k9ZCQiQiIMwaWZT5m7YxIbg0uRuYWE02/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tps going deep', 'https://drive.google.com/file/d/1MBIpP1ImJsINSPi0kWuSe_bpbOa4UJvh/view', 'https://drive.google.com/file/d/1MBIpP1ImJsINSPi0kWuSe_bpbOa4UJvh/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'All about grammar phase 2 composition', 'https://drive.google.com/file/d/1mBwMvst_1DVUgL32UljTd0-XSMF4j-o5/view', 'https://drive.google.com/file/d/1mBwMvst_1DVUgL32UljTd0-XSMF4j-o5/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'All phase 2 of the sections and mistakes', 'https://drive.google.com/file/d/1lFMsbIZ4yixxfjoDgLYtgCBZmdSIjkHX/view', 'https://drive.google.com/file/d/1lFMsbIZ4yixxfjoDgLYtgCBZmdSIjkHX/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Bad habits dos and donts', 'https://drive.google.com/file/d/1HClenydNHZwNNB9e9FPvjVwgTtse2YZg/view', 'https://drive.google.com/file/d/1HClenydNHZwNNB9e9FPvjVwgTtse2YZg/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Grammar problems1 and advanced techniques', 'https://drive.google.com/file/d/1jI8CqDvGIiC2U3U-VCZ6GOvk2qB8UVe8/view', 'https://drive.google.com/file/d/1jI8CqDvGIiC2U3U-VCZ6GOvk2qB8UVe8/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Grammar problems2 and espelho reviews', 'https://drive.google.com/file/d/1DQRpMZradxacnggL3Gug4-2A1Htx-zJQ/view', 'https://drive.google.com/file/d/1DQRpMZradxacnggL3Gug4-2A1Htx-zJQ/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tps and compositions good and bad', 'https://drive.google.com/file/d/1UV5gR3QRvu_a6mBLrEku2fekiauD9RDn/view', 'https://drive.google.com/file/d/1UV5gR3QRvu_a6mBLrEku2fekiauD9RDn/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Possible future questions and summary practice', 'https://drive.google.com/file/d/1w75k7Ryqo7SxAaR3InDG4gmi8Z_GZ9kD/view', 'https://drive.google.com/file/d/1w75k7Ryqo7SxAaR3InDG4gmi8Z_GZ9kD/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Feedback and the composition', 'https://drive.google.com/file/d/16SxUDpWxHTZqmagEHinIjExKq-Knp6fN/view', 'https://drive.google.com/file/d/16SxUDpWxHTZqmagEHinIjExKq-Knp6fN/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'The summary tps', 'https://drive.google.com/file/d/1HeH3ZL2hhg0nJGJiX51ZxvtGo_5S11v_/view', 'https://drive.google.com/file/d/1HeH3ZL2hhg0nJGJiX51ZxvtGo_5S11v_/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'How to deal with impossible translations', 'https://drive.google.com/file/d/1OUClP9ogFHZj8HvSsY7Zww5_hsBkjG4E/view', 'https://drive.google.com/file/d/1OUClP9ogFHZj8HvSsY7Zww5_hsBkjG4E/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Vocabulary improvement', 'https://drive.google.com/file/d/18iFB1GtMebayFn2DQslGNQb7zjOdc9zV/view', 'https://drive.google.com/file/d/18iFB1GtMebayFn2DQslGNQb7zjOdc9zV/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Composition and summary', 'https://drive.google.com/file/d/1nmPhfa7zCbpSitaJMktpXdz7NvkXUQr3/view', 'https://drive.google.com/file/d/1nmPhfa7zCbpSitaJMktpXdz7NvkXUQr3/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Answering the tps exam strategy', 'https://drive.google.com/file/d/1p1Fyi7if0o84_ZfoOhsvOe-FLy81UFUg/view', 'https://drive.google.com/file/d/1p1Fyi7if0o84_ZfoOhsvOe-FLy81UFUg/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'The iades compositions mistakes', 'https://drive.google.com/file/d/1rFUDFc5hPJKpGzUCIRfehPB4aYl-1zCH/view', 'https://drive.google.com/file/d/1rFUDFc5hPJKpGzUCIRfehPB4aYl-1zCH/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tps', 'https://drive.google.com/file/d/1rKKtP6hql0g8KsdG_qqKqoT5uXG8URWN/view', 'https://drive.google.com/file/d/1rKKtP6hql0g8KsdG_qqKqoT5uXG8URWN/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Vocabulary', 'https://drive.google.com/file/d/1BJxKI5Mkot_BZ7rCjRwX-YaPQQ96S5gC/view', 'https://drive.google.com/file/d/1BJxKI5Mkot_BZ7rCjRwX-YaPQQ96S5gC/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Translation', 'https://drive.google.com/file/d/1yUJa7XS2T0wzl7q2k2nqJIlRPAI2tdro/view', 'https://drive.google.com/file/d/1yUJa7XS2T0wzl7q2k2nqJIlRPAI2tdro/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Planning and arguments', 'https://drive.google.com/file/d/14cFDrA2NSSxcu_inLoddPF2bNZXm23_j/view', 'https://drive.google.com/file/d/14cFDrA2NSSxcu_inLoddPF2bNZXm23_j/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tps2', 'https://drive.google.com/file/d/1_hnDYJQtbmLjqiEf7k0r5akQV9we6FAh/view', 'https://drive.google.com/file/d/1_hnDYJQtbmLjqiEf7k0r5akQV9we6FAh/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tps3', 'https://drive.google.com/file/d/1OLk4lw_L6JMHqokeALUDYM3iZLZK5tGW/view', 'https://drive.google.com/file/d/1OLk4lw_L6JMHqokeALUDYM3iZLZK5tGW/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'A full exam', 'https://drive.google.com/file/d/1FPeLvYSMELfKpHXwK8rz4jK4VrhRVTGZ/view', 'https://drive.google.com/file/d/1FPeLvYSMELfKpHXwK8rz4jK4VrhRVTGZ/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Final review', 'https://drive.google.com/file/d/1mjT3TR-vtpQjLY6TakbYhyzke7Q8m9Rr/view', 'https://drive.google.com/file/d/1mjT3TR-vtpQjLY6TakbYhyzke7Q8m9Rr/preview', 208);
  END IF;

  -- Francês
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Francês')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Recommandations pour les etudes phonetique et accents', 'https://drive.google.com/file/d/1N5P7PiG7ajYK-EruNH8oJPUq4DQTR1XL/view', 'https://drive.google.com/file/d/1N5P7PiG7ajYK-EruNH8oJPUq4DQTR1XL/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Articles definis indefinis et contractes', 'https://drive.google.com/file/d/1Orms9AUz5zQrnSz47qr2_cNOS8EilrWd/view', 'https://drive.google.com/file/d/1Orms9AUz5zQrnSz47qr2_cNOS8EilrWd/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Articles definis indefinis et contractes', 'https://drive.google.com/file/d/1rXyMe6mzZidhNY_Mm4tYPJOhUZFXolcE/view', 'https://drive.google.com/file/d/1rXyMe6mzZidhNY_Mm4tYPJOhUZFXolcE/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Phrase neative et phrase interrogative', 'https://drive.google.com/file/d/1qHGraW9ZIXUrXP_N4HllJnuO31RvAhTI/view', 'https://drive.google.com/file/d/1qHGraW9ZIXUrXP_N4HllJnuO31RvAhTI/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Futur simles futur proche', 'https://drive.google.com/file/d/13CLcsGkNiboJO6M7AAtJPXfWXylAzmDw/view', 'https://drive.google.com/file/d/13CLcsGkNiboJO6M7AAtJPXfWXylAzmDw/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Gentre nombre et artciles partitifs', 'https://drive.google.com/file/d/1N58_7FX6zNqmDcVUBxK2TBSBnJosR51v/view', 'https://drive.google.com/file/d/1N58_7FX6zNqmDcVUBxK2TBSBnJosR51v/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Adjectifs possessifs et demonstratifs', 'https://drive.google.com/file/d/1zY2rwqyEx_fqMsY9DS3Uxyu2e9ArTeNJ/view', 'https://drive.google.com/file/d/1zY2rwqyEx_fqMsY9DS3Uxyu2e9ArTeNJ/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Adverbes et pronoms relatifs simples', 'https://drive.google.com/file/d/1DHwT0JME2XHHdHlvpORzZP0g_D7py8rL/view', 'https://drive.google.com/file/d/1DHwT0JME2XHHdHlvpORzZP0g_D7py8rL/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Passe compose', 'https://drive.google.com/file/d/1YE2qkxrmhykJgKxQQCfvVt1BwBFDTNO7/view', 'https://drive.google.com/file/d/1YE2qkxrmhykJgKxQQCfvVt1BwBFDTNO7/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronom cod', 'https://drive.google.com/file/d/1s6hpOOUcMDACrDa0cN6ghEDkaNqNMg0G/view', 'https://drive.google.com/file/d/1s6hpOOUcMDACrDa0cN6ghEDkaNqNMg0G/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronom coi', 'https://drive.google.com/file/d/1dzF9sEP5iHTIvymmOj-IPc0iRaCfcdum/view', 'https://drive.google.com/file/d/1dzF9sEP5iHTIvymmOj-IPc0iRaCfcdum/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronoms en et y', 'https://drive.google.com/file/d/1RF9h20soEYzrhXsEusEkm9K2LvgVoH_3/view', 'https://drive.google.com/file/d/1RF9h20soEYzrhXsEusEkm9K2LvgVoH_3/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Limparfait de lindicatif', 'https://drive.google.com/file/d/1MrJkLZ3JBgoxrh6bJ2AuR_tsGxBt7Ohw/view', 'https://drive.google.com/file/d/1MrJkLZ3JBgoxrh6bJ2AuR_tsGxBt7Ohw/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Plus que parfait et futur anterieur', 'https://drive.google.com/file/d/16jAx5YkE0jT9ylwTJLjxF8ww0paSQVRR/view', 'https://drive.google.com/file/d/16jAx5YkE0jT9ylwTJLjxF8ww0paSQVRR/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronoms possessifs et demonstratifs', 'https://drive.google.com/file/d/1ZGI2vLMCIwAvJdXyeKbcDSLLAMTLhCvR/view', 'https://drive.google.com/file/d/1ZGI2vLMCIwAvJdXyeKbcDSLLAMTLhCvR/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Accord du participe passe', 'https://drive.google.com/file/d/1fmOtkhctHsZfGEeumKW0rfno7uCvWn_x/view', 'https://drive.google.com/file/d/1fmOtkhctHsZfGEeumKW0rfno7uCvWn_x/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Participe present et gerondif', 'https://drive.google.com/file/d/1cP0L-ynbnQmt4t1dDQ3SKe0sjTI9dkau/view', 'https://drive.google.com/file/d/1cP0L-ynbnQmt4t1dDQ3SKe0sjTI9dkau/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Subjonctif present et passe', 'https://drive.google.com/file/d/10WRBGwcWEgrOA7nkaAw-_90Can1lJFID/view', 'https://drive.google.com/file/d/10WRBGwcWEgrOA7nkaAw-_90Can1lJFID/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Conditionnel present et passe', 'https://drive.google.com/file/d/1q8fL92hx4W3hsqF35ERg-pZNbuaLbxGe/view', 'https://drive.google.com/file/d/1q8fL92hx4W3hsqF35ERg-pZNbuaLbxGe/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relations logiques hypotheses', 'https://drive.google.com/file/d/1pw30vf5mCmewXWy1wCXYWVXX25rQfqoY/view', 'https://drive.google.com/file/d/1pw30vf5mCmewXWy1wCXYWVXX25rQfqoY/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relations logiques expression de la cause', 'https://drive.google.com/file/d/1Go37mh3qVH6H-cOY6Dd_bpZmPdEi3F_C/view', 'https://drive.google.com/file/d/1Go37mh3qVH6H-cOY6Dd_bpZmPdEi3F_C/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relations logiques expressions de la consequence et du but', 'https://drive.google.com/file/d/1dgdglrfc5igcoDzBYfTT6fPTXJH28MLm/view', 'https://drive.google.com/file/d/1dgdglrfc5igcoDzBYfTT6fPTXJH28MLm/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Expression de loposition et de la concession', 'https://drive.google.com/file/d/1FGyJkE6tS4CzmupV9jfGlDtavJAOGXf3/view', 'https://drive.google.com/file/d/1FGyJkE6tS4CzmupV9jfGlDtavJAOGXf3/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Laddition lillustration la synthese et la progression', 'https://drive.google.com/file/d/1tsQdNYpDW-ZkgfItsi0kngvm3fNo3yt_/view', 'https://drive.google.com/file/d/1tsQdNYpDW-ZkgfItsi0kngvm3fNo3yt_/preview', 208);
  END IF;

  -- Espanhol
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Espanhol')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Introduccion', 'https://drive.google.com/file/d/11SuP2fYT_s_aLpguIJwVtnQvF_hctiNB/view', 'https://drive.google.com/file/d/11SuP2fYT_s_aLpguIJwVtnQvF_hctiNB/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Presente del modo indicativo 1', 'https://drive.google.com/file/d/1DMF0EKbatQFvOMmhEPIEcASCM2Dr5neQ/view', 'https://drive.google.com/file/d/1DMF0EKbatQFvOMmhEPIEcASCM2Dr5neQ/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Presente modo indicativo 2', 'https://drive.google.com/file/d/1jjkv0Ro6feS1_nqE8H4oXHT42oejw0Uz/view', 'https://drive.google.com/file/d/1jjkv0Ro6feS1_nqE8H4oXHT42oejw0Uz/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Modo indicativo gustar y construcciones valorativas', 'https://drive.google.com/file/d/11oTx8kOp6cH_QivQrhoDHEQRl-pZZ3Qs/view', 'https://drive.google.com/file/d/11oTx8kOp6cH_QivQrhoDHEQRl-pZZ3Qs/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preposiciones 1', 'https://drive.google.com/file/d/1TLHnXz_4ldo1bOC_hmkSU8Am0jPd45sv/view', 'https://drive.google.com/file/d/1TLHnXz_4ldo1bOC_hmkSU8Am0jPd45sv/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preposiciones 2', 'https://drive.google.com/file/d/1NVdH-_IlP6J1ENVKfKQk3G_KPi_8PucX/view', 'https://drive.google.com/file/d/1NVdH-_IlP6J1ENVKfKQk3G_KPi_8PucX/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito perfecto compuesto 1', 'https://drive.google.com/file/d/12HOhpQy8OtUzJBcb86UEZDVbqsn_YcO-/view', 'https://drive.google.com/file/d/12HOhpQy8OtUzJBcb86UEZDVbqsn_YcO-/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito perfecto compuesto 2', 'https://drive.google.com/file/d/1Xt3CZsZd2P88Ic8r5ae7RW_0ddjerPCl/view', 'https://drive.google.com/file/d/1Xt3CZsZd2P88Ic8r5ae7RW_0ddjerPCl/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito perfecto simples 1', 'https://drive.google.com/file/d/1GRqFa04ANRznym3qB0JXrwC7B0rTa55F/view', 'https://drive.google.com/file/d/1GRqFa04ANRznym3qB0JXrwC7B0rTa55F/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito perfecto simples 2', 'https://drive.google.com/file/d/16uU_T53Dhb1fEFmo52AGuGaW0htFsxc8/view', 'https://drive.google.com/file/d/16uU_T53Dhb1fEFmo52AGuGaW0htFsxc8/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Verbos pronominales', 'https://drive.google.com/file/d/1RYT6nfbxTxWACjLsRUOpbB7J97lM-t1Y/view', 'https://drive.google.com/file/d/1RYT6nfbxTxWACjLsRUOpbB7J97lM-t1Y/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Demonstrativos', 'https://drive.google.com/file/d/1WAttS26RS4YtnTf9BVwb0lLtam6c3Ytw/view', 'https://drive.google.com/file/d/1WAttS26RS4YtnTf9BVwb0lLtam6c3Ytw/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronombres posesivos 1', 'https://drive.google.com/file/d/1Zh1KT7W94PCdk7d2rKexgXTDUq-cKSOy/view', 'https://drive.google.com/file/d/1Zh1KT7W94PCdk7d2rKexgXTDUq-cKSOy/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronombres posesivos 2', 'https://drive.google.com/file/d/1RscK4FTNt1uN9RtZt3kmykS2IIaYkRko/view', 'https://drive.google.com/file/d/1RscK4FTNt1uN9RtZt3kmykS2IIaYkRko/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronombre complemento directo', 'https://drive.google.com/file/d/1Jr8QqDRxL6Mq6G5GzM_XteoQ3f1qfyY9/view', 'https://drive.google.com/file/d/1Jr8QqDRxL6Mq6G5GzM_XteoQ3f1qfyY9/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pronombre complemento indirecto', 'https://drive.google.com/file/d/18O1Z8ygJ55T4MYe_LU-toTe3Zc9Hp5TP/view', 'https://drive.google.com/file/d/18O1Z8ygJ55T4MYe_LU-toTe3Zc9Hp5TP/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Perifrasis verbales 1', 'https://drive.google.com/file/d/1bH45WiNINb9RfcIXz9kzOaxauWcjf-9g/view', 'https://drive.google.com/file/d/1bH45WiNINb9RfcIXz9kzOaxauWcjf-9g/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Perifrasis verbales 2', 'https://drive.google.com/file/d/1k0nAEHNnFm1FFX6WfkwZ91TLsh0VPgHt/view', 'https://drive.google.com/file/d/1k0nAEHNnFm1FFX6WfkwZ91TLsh0VPgHt/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito imperfecto1', 'https://drive.google.com/file/d/1gIk030DEOTBTQ0MLqw_r6fEEC7li0KQU/view', 'https://drive.google.com/file/d/1gIk030DEOTBTQ0MLqw_r6fEEC7li0KQU/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Preterito imperfecto2', 'https://drive.google.com/file/d/17gE4sWDE0uugnNrApoec3ZOguP7CZFcs/view', 'https://drive.google.com/file/d/17gE4sWDE0uugnNrApoec3ZOguP7CZFcs/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Imperativo1', 'https://drive.google.com/file/d/11BY5dISBgpmPpMn9TBvhQ7tx8Ko4NF4B/view', 'https://drive.google.com/file/d/11BY5dISBgpmPpMn9TBvhQ7tx8Ko4NF4B/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Imperativo2', 'https://drive.google.com/file/d/142HobqDsNA09t5OyNTnDoQO3B9gJEUPs/view', 'https://drive.google.com/file/d/142HobqDsNA09t5OyNTnDoQO3B9gJEUPs/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Contrastes de preteritos 1', 'https://drive.google.com/file/d/1L76qPf6Pvcod6xY9AcMfjAyhPxc_Q9qg/view', 'https://drive.google.com/file/d/1L76qPf6Pvcod6xY9AcMfjAyhPxc_Q9qg/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Contrrastes de preteritos2', 'https://drive.google.com/file/d/1SS7HxHPPKyGDsLJmN26PpJGwfViO7b8K/view', 'https://drive.google.com/file/d/1SS7HxHPPKyGDsLJmN26PpJGwfViO7b8K/preview', 208);
  END IF;

  -- Economia
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Economia')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Conceitos iniciais', 'https://drive.google.com/file/d/19wwOg90hZRfbbqTIEe-yLJ4IJAMXzrsE/view', 'https://drive.google.com/file/d/19wwOg90hZRfbbqTIEe-yLJ4IJAMXzrsE/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Elasticidade e impostos', 'https://drive.google.com/file/d/1mGbQshmDG3a9_HUTrrw3AYW54e2g5LWs/view', 'https://drive.google.com/file/d/1mGbQshmDG3a9_HUTrrw3AYW54e2g5LWs/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Teeoria do consumidor', 'https://drive.google.com/file/d/17mk3BlhLuv5WX9r6epNR4lCgEnDiVzLS/view', 'https://drive.google.com/file/d/17mk3BlhLuv5WX9r6epNR4lCgEnDiVzLS/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Teroria da firma p1', 'https://drive.google.com/file/d/1r3zZYY7F2CouPEFjIFF9v6XYqCNJ-2oK/view', 'https://drive.google.com/file/d/1r3zZYY7F2CouPEFjIFF9v6XYqCNJ-2oK/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Teoria da firma p2', 'https://drive.google.com/file/d/13mKKpl6-heZg1Upc-jX576xVnBnu60wt/view', 'https://drive.google.com/file/d/13mKKpl6-heZg1Upc-jX576xVnBnu60wt/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tconcorrencia perfeita', 'https://drive.google.com/file/d/1tbRrlZgKdq5iuk-0up6skytXJIRPzDMH/view', 'https://drive.google.com/file/d/1tbRrlZgKdq5iuk-0up6skytXJIRPzDMH/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Monopolio', 'https://drive.google.com/file/d/1B89nrc_NBEXhbwjTe7cBBnBrIrudIQDw/view', 'https://drive.google.com/file/d/1B89nrc_NBEXhbwjTe7cBBnBrIrudIQDw/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oligopolio', 'https://drive.google.com/file/d/1I3ddIMw75LQT3o1QKb_-d8U4L8Brrecd/view', 'https://drive.google.com/file/d/1I3ddIMw75LQT3o1QKb_-d8U4L8Brrecd/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Contabilidade nacional', 'https://drive.google.com/file/d/1ODnVietHxSCsnllHK5uYW8EprQ-57byC/view', 'https://drive.google.com/file/d/1ODnVietHxSCsnllHK5uYW8EprQ-57byC/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Instrumentos politica comercio exterior', 'https://drive.google.com/file/d/14Q5pb8-m2RLvKlIWzq3JXQQ06tbZscDC/view', 'https://drive.google.com/file/d/14Q5pb8-m2RLvKlIWzq3JXQQ06tbZscDC/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Liberalismo comercial critica cepal', 'https://drive.google.com/file/d/1IKN8CLgdPk_rfYR8yTsMGq8mhf1qxfZE/view', 'https://drive.google.com/file/d/1IKN8CLgdPk_rfYR8yTsMGq8mhf1qxfZE/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Teorias classica keynesiana', 'https://drive.google.com/file/d/1PC-PFv2SZSiduM4ORTwIqRyfIjnZgqa7/view', 'https://drive.google.com/file/d/1PC-PFv2SZSiduM4ORTwIqRyfIjnZgqa7/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Moedas bancos', 'https://drive.google.com/file/d/1vyM_7vt6v6ZqGQyWiKX-sHc-7HN-OVye/view', 'https://drive.google.com/file/d/1vyM_7vt6v6ZqGQyWiKX-sHc-7HN-OVye/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Polilitica monetaria', 'https://drive.google.com/file/d/1TYj5LiUAqFPyWexQmLChoNKRjCJXKaJe/view', 'https://drive.google.com/file/d/1TYj5LiUAqFPyWexQmLChoNKRjCJXKaJe/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica fiscal', 'https://drive.google.com/file/d/1xeeSeUXAjmTSMiWfRqyk-9vqwEXA1SaF/view', 'https://drive.google.com/file/d/1xeeSeUXAjmTSMiWfRqyk-9vqwEXA1SaF/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Tradeoff politica economica desenvolvimento', 'https://drive.google.com/file/d/1vs_MQAJt7KSInhdFjfmzMY-vUmYUeyrz/view', 'https://drive.google.com/file/d/1vs_MQAJt7KSInhdFjfmzMY-vUmYUeyrz/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Balanco de pagamentos', 'https://drive.google.com/file/d/1Lhuy1i-PTjCmFOsp64riruebOAO2Ztkv/view', 'https://drive.google.com/file/d/1Lhuy1i-PTjCmFOsp64riruebOAO2Ztkv/preview', 109);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Cambio', 'https://drive.google.com/file/d/1aOz9d7VMCSsy1pZOIay2lN7jsQBeCIrW/view', 'https://drive.google.com/file/d/1aOz9d7VMCSsy1pZOIay2lN7jsQBeCIrW/preview', 110);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Modelo is lm bp', 'https://drive.google.com/file/d/1KB2y_Jo_ytXnjIEhoZWUYdiS7KBoY7sX/view', 'https://drive.google.com/file/d/1KB2y_Jo_ytXnjIEhoZWUYdiS7KBoY7sX/preview', 111);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Fluxos internacionais bens capital servicos', 'https://drive.google.com/file/d/1UGZ-2Ec1QLrtWsNidT3DyiWRVlVIhFPN/view', 'https://drive.google.com/file/d/1UGZ-2Ec1QLrtWsNidT3DyiWRVlVIhFPN/preview', 112);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Economia brasileira ixi cafeeira', 'https://drive.google.com/file/d/1LDNVAVDkFUWOCs2bpwsUeTCd6BOjI2jr/view', 'https://drive.google.com/file/d/1LDNVAVDkFUWOCs2bpwsUeTCd6BOjI2jr/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Primeira republica a rev 30', 'https://drive.google.com/file/d/16FyXTZGLa9gOaOiw3778AU9Di_2RnyON/view', 'https://drive.google.com/file/d/16FyXTZGLa9gOaOiw3778AU9Di_2RnyON/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Industrializacao 1930 a 1945', 'https://drive.google.com/file/d/13SeWGbS7K6xHfQeuIQ9GlQbvR5j90MEu/view', 'https://drive.google.com/file/d/13SeWGbS7K6xHfQeuIQ9GlQbvR5j90MEu/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Pos guerra segundo gov vargas planos de metas', 'https://drive.google.com/file/d/1oySsKcOfMtc9ooDnNGebm54uz9DgwfSg/view', 'https://drive.google.com/file/d/1oySsKcOfMtc9ooDnNGebm54uz9DgwfSg/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Crise 1960 PAEG', 'https://drive.google.com/file/d/1vGRpzzAmGX4PrYmeaT-qtUcU_IrYRMcR/view', 'https://drive.google.com/file/d/1vGRpzzAmGX4PrYmeaT-qtUcU_IrYRMcR/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Milagre economico brasileiro', 'https://drive.google.com/file/d/1mvPVybBR5DU755vjCYgZo5iXxvmPq8iU/view', 'https://drive.google.com/file/d/1mvPVybBR5DU755vjCYgZo5iXxvmPq8iU/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'II PND ajuste externo', 'https://drive.google.com/file/d/1xGxjC9yETi6JQ5RINv7J8cDQdW0x3brQ/view', 'https://drive.google.com/file/d/1xGxjC9yETi6JQ5RINv7J8cDQdW0x3brQ/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Planos estabilizacao 1985 1989', 'https://drive.google.com/file/d/1PkBiYomWEa_klzwvsv9lTiZYzm39j3Jq/view', 'https://drive.google.com/file/d/1PkBiYomWEa_klzwvsv9lTiZYzm39j3Jq/preview', 208);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Anos 90 aberturas privatizacoes', 'https://drive.google.com/file/d/1lhcL7DBzDUDGSbZyxqr0m59cMpixYCLU/view', 'https://drive.google.com/file/d/1lhcL7DBzDUDGSbZyxqr0m59cMpixYCLU/preview', 209);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Consolidacao da estabilizacao reconstrucao institucional', 'https://drive.google.com/file/d/1a9Hz8gR4eHzNyLjBVeViG6fuFx5n6UI1/view', 'https://drive.google.com/file/d/1a9Hz8gR4eHzNyLjBVeViG6fuFx5n6UI1/preview', 210);
  END IF;

  -- Direito Interno
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Direito Interno')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Normas juridicas', 'https://drive.google.com/file/d/1qjcc8l_Z4ZSwNMLg2NGIsFy4Z5oZO89h/view', 'https://drive.google.com/file/d/1qjcc8l_Z4ZSwNMLg2NGIsFy4Z5oZO89h/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Personalidade juridica', 'https://drive.google.com/file/d/1xobd2xZUWudKQS3FlE0dG4PTCIUS2MZ2/view', 'https://drive.google.com/file/d/1xobd2xZUWudKQS3FlE0dG4PTCIUS2MZ2/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Constituicao controle constitucionalidade', 'https://drive.google.com/file/d/1otqCq8ZHe5eLNv8b4uZsZpRJVs0BpSk9/view', 'https://drive.google.com/file/d/1otqCq8ZHe5eLNv8b4uZsZpRJVs0BpSk9/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Conntrole constitucionalidade', 'https://drive.google.com/file/d/1Ke7bIjPh7YxnMETCEhKsv7nlRGtg4k-3/view', 'https://drive.google.com/file/d/1Ke7bIjPh7YxnMETCEhKsv7nlRGtg4k-3/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estado', 'https://drive.google.com/file/d/1aX_VDVP9CepDFXPzHWKxR-XRBFJbUphy/view', 'https://drive.google.com/file/d/1aX_VDVP9CepDFXPzHWKxR-XRBFJbUphy/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estado democratico direito', 'https://drive.google.com/file/d/10YCRPD2cDsYImjKKMHFqLke6WN1e3J2l/view', 'https://drive.google.com/file/d/10YCRPD2cDsYImjKKMHFqLke6WN1e3J2l/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Organizacao competencia poderes', 'https://drive.google.com/file/d/1pfxbODufVW2tm4VGs5zSq-0FSt8m68gS/view', 'https://drive.google.com/file/d/1pfxbODufVW2tm4VGs5zSq-0FSt8m68gS/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direitos fundamentais', 'https://drive.google.com/file/d/1lz_Ob2n-yCKGu0aiEGVDueEjzKpmB8Zg/view', 'https://drive.google.com/file/d/1lz_Ob2n-yCKGu0aiEGVDueEjzKpmB8Zg/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Adm publica', 'https://drive.google.com/file/d/1em1crXtzOT6KsUZxCbr9gesDgCi484Ie/view', 'https://drive.google.com/file/d/1em1crXtzOT6KsUZxCbr9gesDgCi484Ie/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Atos administrativos', 'https://drive.google.com/file/d/1r5C-WSQn0LjRXNBebh9NrSkcmePGrrNr/view', 'https://drive.google.com/file/d/1r5C-WSQn0LjRXNBebh9NrSkcmePGrrNr/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Contratacao adm publica', 'https://drive.google.com/file/d/11dAuF49pVPyGHbdYQ_r3Z41jV90BkNPr/view', 'https://drive.google.com/file/d/11dAuF49pVPyGHbdYQ_r3Z41jV90BkNPr/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Resp civil estado', 'https://drive.google.com/file/d/1NDbk522BExrLTFuGFiUBoKqdIrW1ShU5/view', 'https://drive.google.com/file/d/1NDbk522BExrLTFuGFiUBoKqdIrW1ShU5/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direitos deveres servidores publicos', 'https://drive.google.com/file/d/19-bqHTqaZPqf3JMwlnB79lgNM4pMWLj5/view', 'https://drive.google.com/file/d/19-bqHTqaZPqf3JMwlnB79lgNM4pMWLj5/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Regime juridico servico exterior', 'https://drive.google.com/file/d/1-xia_Hp4jjDLfkxK4jrNuQ1YewPvkXSm/view', 'https://drive.google.com/file/d/1-xia_Hp4jjDLfkxK4jrNuQ1YewPvkXSm/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Financas publicas', 'https://drive.google.com/file/d/1pN4whhyBYbRSWSsw8KvDA9TyBOjj7jz8/view', 'https://drive.google.com/file/d/1pN4whhyBYbRSWSsw8KvDA9TyBOjj7jz8/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacional privado lindb', 'https://drive.google.com/file/d/19ORZwLmnMJzlawSNfOX1FK_PeeBN8RYd/view', 'https://drive.google.com/file/d/19ORZwLmnMJzlawSNfOX1FK_PeeBN8RYd/preview', 108);
  END IF;

  -- Geografia
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Geografia')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Historia geografia', 'https://drive.google.com/file/d/16ikDG560clJixXEeKl-615otamtefwkI/view', 'https://drive.google.com/file/d/16ikDG560clJixXEeKl-615otamtefwkI/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Conceietos fundamentais', 'https://drive.google.com/file/d/174sOYRNVHNzBqrJJiBo62_kU2q_71sPr/view', 'https://drive.google.com/file/d/174sOYRNVHNzBqrJJiBo62_kU2q_71sPr/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Urbanizacao formacao redes cidades', 'https://drive.google.com/file/d/1Y17eUqOx56W1jcasUpfNr7UDR6r7m3_z/view', 'https://drive.google.com/file/d/1Y17eUqOx56W1jcasUpfNr7UDR6r7m3_z/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Rede urbana brasileira papel cidades medias modernizacao', 'https://drive.google.com/file/d/1uUGfjlLfoJ4XDZb85fvAq8jowMr_Pomv/view', 'https://drive.google.com/file/d/1uUGfjlLfoJ4XDZb85fvAq8jowMr_Pomv/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Rede urbana brasileira papel cidade media modernizacao', 'https://drive.google.com/file/d/1Q8wauSha-oBgqgWtthgV-gfhDENYxX1U/view', 'https://drive.google.com/file/d/1Q8wauSha-oBgqgWtthgV-gfhDENYxX1U/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Rede urbana papel cidades medias modernizacao p2', 'https://drive.google.com/file/d/1PYhZauONjr2iA3-L-NwSXrxvbzq_DFbQ/view', 'https://drive.google.com/file/d/1PYhZauONjr2iA3-L-NwSXrxvbzq_DFbQ/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Dinamica demografica mundial distribuicao populacao', 'https://drive.google.com/file/d/1zLSIfRg93AhYyNrWU6CBqA4kTOW0VP73/view', 'https://drive.google.com/file/d/1zLSIfRg93AhYyNrWU6CBqA4kTOW0VP73/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Dinamica demografica brasileira estrutura etaria', 'https://drive.google.com/file/d/1OkMEKp4syMXaIsx9zZyyHTscOCLOjeag/view', 'https://drive.google.com/file/d/1OkMEKp4syMXaIsx9zZyyHTscOCLOjeag/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Migracoes espaco mundial p1', 'https://drive.google.com/file/d/17XeDsKecNI3F8tOIFQycKM0yEfxgv297/view', 'https://drive.google.com/file/d/17XeDsKecNI3F8tOIFQycKM0yEfxgv297/preview', 9);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Migracoes espaco mundial p2', 'https://drive.google.com/file/d/1qlqMry6CJfNKlp9GXmx4fOvxqO0GbrjO/view', 'https://drive.google.com/file/d/1qlqMry6CJfNKlp9GXmx4fOvxqO0GbrjO/preview', 10);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Divisao internacional trabalho reordenamentos pos fordista', 'https://drive.google.com/file/d/1Hqz6m3yJh3QXjgCzExAh-i1rIoLMOiTS/view', 'https://drive.google.com/file/d/1Hqz6m3yJh3QXjgCzExAh-i1rIoLMOiTS/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Globalizacao integracao regional', 'https://drive.google.com/file/d/18rpRfHyoTt8bY2Lvd2aZSsDiQBdArR6Z/view', 'https://drive.google.com/file/d/18rpRfHyoTt8bY2Lvd2aZSsDiQBdArR6Z/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Inddustrializacao brasileira p1', 'https://drive.google.com/file/d/1cglunJqg5nnHNzfsYFT-FdCDx0MiZAtA/view', 'https://drive.google.com/file/d/1cglunJqg5nnHNzfsYFT-FdCDx0MiZAtA/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Industrializacao brasileira p2', 'https://drive.google.com/file/d/1Qxa0EYGsitlOwX7GdmD3NEwaileByMXX/view', 'https://drive.google.com/file/d/1Qxa0EYGsitlOwX7GdmD3NEwaileByMXX/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Fontes energia', 'https://drive.google.com/file/d/1vnEvwLdG97fD_LxLYKINTii8W9r_3S_2/view', 'https://drive.google.com/file/d/1vnEvwLdG97fD_LxLYKINTii8W9r_3S_2/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Fontes energia br', 'https://drive.google.com/file/d/1WJsTC1oHieFwRUWXt-m8IxeS1ten6J4K/view', 'https://drive.google.com/file/d/1WJsTC1oHieFwRUWXt-m8IxeS1ten6J4K/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Logistica espaco mundial e br', 'https://drive.google.com/file/d/1aJZMJwlTK_sHiFTGOkAsRpvD4ES6mTIU/view', 'https://drive.google.com/file/d/1aJZMJwlTK_sHiFTGOkAsRpvD4ES6mTIU/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Espaco agropecuario mundial', 'https://drive.google.com/file/d/1tXBklaRlrl-gppxOxkYQXmr6cyxGx9AI/view', 'https://drive.google.com/file/d/1tXBklaRlrl-gppxOxkYQXmr6cyxGx9AI/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estruturacao funcionamento agronegocio br', 'https://drive.google.com/file/d/1q1g3BI8sDTHawViY8i4b1Uw4skTdL1Jy/view', 'https://drive.google.com/file/d/1q1g3BI8sDTHawViY8i4b1Uw4skTdL1Jy/preview', 109);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estrutura fundiaria br', 'https://drive.google.com/file/d/1ABxJwsguBvVsktEhoEUmnkcqyUNzY1PN/view', 'https://drive.google.com/file/d/1ABxJwsguBvVsktEhoEUmnkcqyUNzY1PN/preview', 110);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Geografia politica relacoes espaco poder', 'https://drive.google.com/file/d/1c7wH6E2DlZmucz_3PEch6hkEkiGi-PS6/view', 'https://drive.google.com/file/d/1c7wH6E2DlZmucz_3PEch6hkEkiGi-PS6/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Geopolitica hotspots geopolitica br', 'https://drive.google.com/file/d/1_B-08AaFDFeURG6BnRvL3VxEwyrFexc3/view', 'https://drive.google.com/file/d/1_B-08AaFDFeURG6BnRvL3VxEwyrFexc3/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Integracao territorio faixa fronteira', 'https://drive.google.com/file/d/1gCh5uSwHlKmCntusDcUMlKs6XLMBHIa6/view', 'https://drive.google.com/file/d/1gCh5uSwHlKmCntusDcUMlKs6XLMBHIa6/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Ordenamento territorial brasil', 'https://drive.google.com/file/d/1tGSosHOmxd88q1Pr6BUBhUtIu84Io8ip/view', 'https://drive.google.com/file/d/1tGSosHOmxd88q1Pr6BUBhUtIu84Io8ip/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Biomas dominios morfoclimaticos', 'https://drive.google.com/file/d/13gCocSYvNjsc_iBcGxN3FxRVhfBnYzAv/view', 'https://drive.google.com/file/d/13gCocSYvNjsc_iBcGxN3FxRVhfBnYzAv/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Recursos hidricos hidrogeopolitica', 'https://drive.google.com/file/d/1eDxTpXsgF0Gm6chp6PVbJewxJflHjf-o/view', 'https://drive.google.com/file/d/1eDxTpXsgF0Gm6chp6PVbJewxJflHjf-o/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Ordem ambiental mundial', 'https://drive.google.com/file/d/1XVvrLRZtglDMgO3yp9S76kJxrl7b2CA5/view', 'https://drive.google.com/file/d/1XVvrLRZtglDMgO3yp9S76kJxrl7b2CA5/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Politica ambiental br', 'https://drive.google.com/file/d/1f_28pNdSUfc2RnwlcdVMaJM_03GbanQM/view', 'https://drive.google.com/file/d/1f_28pNdSUfc2RnwlcdVMaJM_03GbanQM/preview', 208);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Regionalizacao br espaco amazonico', 'https://drive.google.com/file/d/16y1YTMRLL4nV6eemEH2ROGyuiZMqmtWK/view', 'https://drive.google.com/file/d/16y1YTMRLL4nV6eemEH2ROGyuiZMqmtWK/preview', 209);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Regionalizacao br ne centro sul', 'https://drive.google.com/file/d/1EIDjfHRL9zN0Nn0SrcaX3n9fp3lYOGBi/view', 'https://drive.google.com/file/d/1EIDjfHRL9zN0Nn0SrcaX3n9fp3lYOGBi/preview', 210);
  END IF;

  -- Direito Internacional
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Direito Internacional')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Fundamentos', 'https://drive.google.com/file/d/1tRSFvX2i3Oy7RKeZY7r5MJSFKqlABfVh/view', 'https://drive.google.com/file/d/1tRSFvX2i3Oy7RKeZY7r5MJSFKqlABfVh/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Fontes nao convencionais', 'https://drive.google.com/file/d/1k5KR27vi5SaGzjPweJOguS7r_K9KRzeq/view', 'https://drive.google.com/file/d/1k5KR27vi5SaGzjPweJOguS7r_K9KRzeq/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito dos tratados p1', 'https://drive.google.com/file/d/1UPYuPklLaZsanixDxbto_26S6ZM8GXMj/view', 'https://drive.google.com/file/d/1UPYuPklLaZsanixDxbto_26S6ZM8GXMj/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito dos tratados p2', 'https://drive.google.com/file/d/1jFCkawzT6QOFych19WCYBabhCNU5Yin3/view', 'https://drive.google.com/file/d/1jFCkawzT6QOFych19WCYBabhCNU5Yin3/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estados p1', 'https://drive.google.com/file/d/12NQpcpRwvWw1nSRwOZRzHm3DgMp_L1ix/view', 'https://drive.google.com/file/d/12NQpcpRwvWw1nSRwOZRzHm3DgMp_L1ix/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estados p2', 'https://drive.google.com/file/d/13n6Pj5XNKsi6rGr6-89Ju6GNmmhICiQu/view', 'https://drive.google.com/file/d/13n6Pj5XNKsi6rGr6-89Ju6GNmmhICiQu/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Estados p3', 'https://drive.google.com/file/d/1U2FEf7JEKFQxJZ0egzlZ6R3m-HyngaoX/view', 'https://drive.google.com/file/d/1U2FEf7JEKFQxJZ0egzlZ6R3m-HyngaoX/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Revisao simulado', 'https://drive.google.com/file/d/18hrYfWBiNrcXNr6C2DmNPypiHD-GIMKG/view', 'https://drive.google.com/file/d/18hrYfWBiNrcXNr6C2DmNPypiHD-GIMKG/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Organizacoes internacionais', 'https://drive.google.com/file/d/1r9x7Gjhga2cpJz4PUOBuKdo3hN0YQyrN/view', 'https://drive.google.com/file/d/1r9x7Gjhga2cpJz4PUOBuKdo3hN0YQyrN/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Idireitos humanos', 'https://drive.google.com/file/d/1oqR1Y_mp4a05A1vCcmTMb9dWf_cUj08o/view', 'https://drive.google.com/file/d/1oqR1Y_mp4a05A1vCcmTMb9dWf_cUj08o/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Imunidade Estado Estrangeiro', 'https://drive.google.com/file/d/1nhouOUJoifhty35hYss5aM5DS7AXFvsG/view', 'https://drive.google.com/file/d/1nhouOUJoifhty35hYss5aM5DS7AXFvsG/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Imunidades diplomaticas consulares', 'https://drive.google.com/file/d/1-1ipYuz0bAsLV10OiHKQqo_1b1rbfM2I/view', 'https://drive.google.com/file/d/1-1ipYuz0bAsLV10OiHKQqo_1b1rbfM2I/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Resp internacional', 'https://drive.google.com/file/d/19_HgPwQmCpPpHeD-qPghisC_893GFJ0P/view', 'https://drive.google.com/file/d/19_HgPwQmCpPpHeD-qPghisC_893GFJ0P/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Solucao de controversias p1', 'https://drive.google.com/file/d/10PhMUsQvPBIEyF7tKBShYBgiwIJ8YY12/view', 'https://drive.google.com/file/d/10PhMUsQvPBIEyF7tKBShYBgiwIJ8YY12/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Solucoes de controversias p2', 'https://drive.google.com/file/d/1p4av1Vjt41CbnSn885m2Sz_W0D9O6lfC/view', 'https://drive.google.com/file/d/1p4av1Vjt41CbnSn885m2Sz_W0D9O6lfC/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Revisao simulado', 'https://drive.google.com/file/d/1TtPUlDEVhz7Dkum_fswdTlwkiCPJrals/view', 'https://drive.google.com/file/d/1TtPUlDEVhz7Dkum_fswdTlwkiCPJrals/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Meios coercitivos forca', 'https://drive.google.com/file/d/1_3t0U_D3AsyDO-cf_0RHSr6W95GRdFxT/view', 'https://drive.google.com/file/d/1_3t0U_D3AsyDO-cf_0RHSr6W95GRdFxT/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Sistema seguranca coletiva', 'https://drive.google.com/file/d/1O_l4_spvvYqEMFI9xwRUhj0jd4L_bZPX/view', 'https://drive.google.com/file/d/1O_l4_spvvYqEMFI9xwRUhj0jd4L_bZPX/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacional penal', 'https://drive.google.com/file/d/1oaXCkeTpkd1uBSGOGIeVr0P0HPm-Sqcx/view', 'https://drive.google.com/file/d/1oaXCkeTpkd1uBSGOGIeVr0P0HPm-Sqcx/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacinal refugiados', 'https://drive.google.com/file/d/1YrBYUpstAQ2SkIMblF2Nya2sqidgGyh6/view', 'https://drive.google.com/file/d/1YrBYUpstAQ2SkIMblF2Nya2sqidgGyh6/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacional economico p1', 'https://drive.google.com/file/d/11yZ7Dn-U8PnzETIZqHhLtKTjt2oJkg0U/view', 'https://drive.google.com/file/d/11yZ7Dn-U8PnzETIZqHhLtKTjt2oJkg0U/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacinal economico p2', 'https://drive.google.com/file/d/1FMvaBV_V4gItzW45k5mYP_GzINqbnEb9/view', 'https://drive.google.com/file/d/1FMvaBV_V4gItzW45k5mYP_GzINqbnEb9/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direito internacional economico p3', 'https://drive.google.com/file/d/1NdK5XfLdlycOU1PuF9V4qjAUFK0ERhiN/view', 'https://drive.google.com/file/d/1NdK5XfLdlycOU1PuF9V4qjAUFK0ERhiN/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Revisao simulado', 'https://drive.google.com/file/d/1rGU50WXgnaJdctELZA-7YOBayqDRFsU4/view', 'https://drive.google.com/file/d/1rGU50WXgnaJdctELZA-7YOBayqDRFsU4/preview', 208);
  END IF;

  -- Política Internacional
  SELECT id INTO sid FROM subjects WHERE lower(trim(name)) = lower(trim('Política Internacional')) LIMIT 1;
  IF sid IS NOT NULL THEN
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'ONU', 'https://drive.google.com/file/d/1Sfk4X9y5Rg4BX948t4tKHjX901lvjac7/view', 'https://drive.google.com/file/d/1Sfk4X9y5Rg4BX948t4tKHjX901lvjac7/preview', 1);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Operacoes de paz p1', 'https://drive.google.com/file/d/14k6ynpoEPJKatM0xfRbBzbxfexMzlZ8d/view', 'https://drive.google.com/file/d/14k6ynpoEPJKatM0xfRbBzbxfexMzlZ8d/preview', 2);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Operacoes de paz p2', 'https://drive.google.com/file/d/1DgkjWuI0_OWPnMys1iwN_qi1DVqYROdV/view', 'https://drive.google.com/file/d/1DgkjWuI0_OWPnMys1iwN_qi1DVqYROdV/preview', 3);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Terrorismo', 'https://drive.google.com/file/d/1kyfmSlIj8vNimb3rT6yTg3xGmO3xLEF8/view', 'https://drive.google.com/file/d/1kyfmSlIj8vNimb3rT6yTg3xGmO3xLEF8/preview', 4);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Narcotrafico crimes internacionais ciberneticos', 'https://drive.google.com/file/d/19vGtpHoWtQENo46Knn5T56gNF7SnhH8q/view', 'https://drive.google.com/file/d/19vGtpHoWtQENo46Knn5T56gNF7SnhH8q/preview', 5);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Nao proliferacao nuclear', 'https://drive.google.com/file/d/1vAl78tdERJGt-NepYj5K6vJ8UZOjztME/view', 'https://drive.google.com/file/d/1vAl78tdERJGt-NepYj5K6vJ8UZOjztME/preview', 6);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Meio ambiente', 'https://drive.google.com/file/d/1Nzo7ROmHONZ5ceKV7D4uj6hm6eKykC8z/view', 'https://drive.google.com/file/d/1Nzo7ROmHONZ5ceKV7D4uj6hm6eKykC8z/preview', 7);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Direitos humanos', 'https://drive.google.com/file/d/1yCHM-Sj7UP5WPKb5reGiL8qVi68vqksv/view', 'https://drive.google.com/file/d/1yCHM-Sj7UP5WPKb5reGiL8qVi68vqksv/preview', 8);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Comercio internacional 1', 'https://drive.google.com/file/d/1Lbht8wSKew-d3eXbD81_k53h7OUAkrpw/view', 'https://drive.google.com/file/d/1Lbht8wSKew-d3eXbD81_k53h7OUAkrpw/preview', 9);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Comercio internacional 2', 'https://drive.google.com/file/d/1rK86v9zW6olCefh7QkzGqkjNwkrsbuv_/view', 'https://drive.google.com/file/d/1rK86v9zW6olCefh7QkzGqkjNwkrsbuv_/preview', 10);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Sistema financeiro internacional', 'https://drive.google.com/file/d/1wrX3_M4W_gzOIIiqWjYlAdjgHYkGM55E/view', 'https://drive.google.com/file/d/1wrX3_M4W_gzOIIiqWjYlAdjgHYkGM55E/preview', 11);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'PEB I', 'https://drive.google.com/file/d/1si_80ac2x8LOOB5CGir__khHblSOEKWE/view', 'https://drive.google.com/file/d/1si_80ac2x8LOOB5CGir__khHblSOEKWE/preview', 101);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'PEB II', 'https://drive.google.com/file/d/1Al-KXSmYLQKcfXuvHmZ4Z9jpBOZ9CDhD/view', 'https://drive.google.com/file/d/1Al-KXSmYLQKcfXuvHmZ4Z9jpBOZ9CDhD/preview', 102);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'PEB III', 'https://drive.google.com/file/d/1wSTR4MDtTiBXeB-XrJBIe5IEVnaLyt1O/view', 'https://drive.google.com/file/d/1wSTR4MDtTiBXeB-XrJBIe5IEVnaLyt1O/preview', 103);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'PEB IV', 'https://drive.google.com/file/d/1PSe02eo4MTAe_r1JHAglRMPrSNXciwiT/view', 'https://drive.google.com/file/d/1PSe02eo4MTAe_r1JHAglRMPrSNXciwiT/preview', 104);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'PEB V', 'https://drive.google.com/file/d/1Fl8tl6t-SMqwqLHE_lWMQTIzPx0WtEGJ/view', 'https://drive.google.com/file/d/1Fl8tl6t-SMqwqLHE_lWMQTIzPx0WtEGJ/preview', 105);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-ARG', 'https://drive.google.com/file/d/17QSMH_hpwAQXARof4MPqfCMSY2HDyPZH/view', 'https://drive.google.com/file/d/17QSMH_hpwAQXARof4MPqfCMSY2HDyPZH/preview', 106);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-EUA', 'https://drive.google.com/file/d/1i_kc3970PidEVhMLmKelxZjScCmxakcW/view', 'https://drive.google.com/file/d/1i_kc3970PidEVhMLmKelxZjScCmxakcW/preview', 107);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-CHINA', 'https://drive.google.com/file/d/1RLzBD42HZiWj3gxTt-XWG3WOtNNJkD0I/view', 'https://drive.google.com/file/d/1RLzBD42HZiWj3gxTt-XWG3WOtNNJkD0I/preview', 108);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-INDIA', 'https://drive.google.com/file/d/1tAJCCE1apxbhoOYEldcSQit4zYrH7Shv/view', 'https://drive.google.com/file/d/1tAJCCE1apxbhoOYEldcSQit4zYrH7Shv/preview', 109);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-AMERICA LATINA', 'https://drive.google.com/file/d/18asP45DH33Ajq4JssJwM4-dvWmOB06yR/view', 'https://drive.google.com/file/d/18asP45DH33Ajq4JssJwM4-dvWmOB06yR/preview', 110);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-JAPAO BR-RUSSIA', 'https://drive.google.com/file/d/1k6_1sg5dHjODXfd2wPXduVbZDyanOvuM/view', 'https://drive.google.com/file/d/1k6_1sg5dHjODXfd2wPXduVbZDyanOvuM/preview', 111);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Relacoes BR-Oriente Medio-Africa', 'https://drive.google.com/file/d/1AmVd8affkyZjMw03Y5tUhw95YmSwHOiW/view', 'https://drive.google.com/file/d/1AmVd8affkyZjMw03Y5tUhw95YmSwHOiW/preview', 112);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Mercosul p1', 'https://drive.google.com/file/d/1Dq6x3xk0dsMxC1ea8hc04kWDi-YO93pJ/view', 'https://drive.google.com/file/d/1Dq6x3xk0dsMxC1ea8hc04kWDi-YO93pJ/preview', 201);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Mercosul p2', 'https://drive.google.com/file/d/1vJbHcOizJLChHn6NNJEhXHANadmTuiZ7/view', 'https://drive.google.com/file/d/1vJbHcOizJLChHn6NNJEhXHANadmTuiZ7/preview', 202);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Integracoes latino americanas', 'https://drive.google.com/file/d/1sWQAmw3Ih9Hu6_IuugozLZ3XyF_-Kh-x/view', 'https://drive.google.com/file/d/1sWQAmw3Ih9Hu6_IuugozLZ3XyF_-Kh-x/preview', 203);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Integracao da europa 1', 'https://drive.google.com/file/d/1k3QKlUQfBqsni8BKvTOsOV5JLgTjuVA5/view', 'https://drive.google.com/file/d/1k3QKlUQfBqsni8BKvTOsOV5JLgTjuVA5/preview', 204);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Integracao da europa 2', 'https://drive.google.com/file/d/1tpBlWN53kPWudQIu6TsvAeXP7bSK-2c_/view', 'https://drive.google.com/file/d/1tpBlWN53kPWudQIu6TsvAeXP7bSK-2c_/preview', 205);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oriente medio 1', 'https://drive.google.com/file/d/1YMXkCgCtHORiZbM2Onk0cjihiiyj8t7w/view', 'https://drive.google.com/file/d/1YMXkCgCtHORiZbM2Onk0cjihiiyj8t7w/preview', 206);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oriente medio 2', 'https://drive.google.com/file/d/1AqWQQ7xAdAg7Vc3ha8yoAqmngl5fEvh6/view', 'https://drive.google.com/file/d/1AqWQQ7xAdAg7Vc3ha8yoAqmngl5fEvh6/preview', 207);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oriente medio 3', 'https://drive.google.com/file/d/1Xo5RHLo4C1pPiNjdcppnRGalYdxEoGin/view', 'https://drive.google.com/file/d/1Xo5RHLo4C1pPiNjdcppnRGalYdxEoGin/preview', 208);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oea cplp t', 'https://drive.google.com/file/d/15fucVlunR1CZ1zyCw-qaacFnTclncGE9/view', 'https://drive.google.com/file/d/15fucVlunR1CZ1zyCw-qaacFnTclncGE9/preview', 209);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Oteoria das relacoes internacionais', 'https://drive.google.com/file/d/1o1SjbGgT4PfZXWG1jBxD9KzNhdRJ4RZF/view', 'https://drive.google.com/file/d/1o1SjbGgT4PfZXWG1jBxD9KzNhdRJ4RZF/preview', 210);
    INSERT INTO lessons (subject_id, title, drive_url, embed_url, order_index) VALUES (sid, 'Teoria das relacoes internacionais 2', 'https://drive.google.com/file/d/1DPAoUb2z7VtHm0wk_hqBzQybKaSHipTH/view', 'https://drive.google.com/file/d/1DPAoUb2z7VtHm0wk_hqBzQybKaSHipTH/preview', 200);
  END IF;

END $$;